In [164]:
import pandas as pd
import numpy as np
#linking csv to pandas
df=pd.read_csv('African_crises_dataset.csv')  #if it's in dossier: pyhton\\
type(df)

pandas.core.frame.DataFrame

## Equilbrage-Imbalanced Learning

In [ ]:
#Data Transormation
# Ensure that all columns are NUMERICAL to be able to use imblearn
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
for col in df.columns:
    df[col]=le.fit_transform(df[col])  # Apply the LabelEncoder()
    print(col, "column:", df[col].value_counts().to_dict())

country_number column: {4: 155, 9: 114, 12: 90, 0: 85, 1: 77, 7: 75, 10: 75, 11: 72, 6: 68, 5: 67, 3: 63, 8: 60, 2: 58}
country_code column: {4: 155, 10: 114, 12: 90, 3: 85, 0: 77, 6: 75, 9: 75, 11: 72, 7: 68, 5: 67, 2: 63, 8: 60, 1: 58}
country column: {3: 155, 9: 114, 12: 90, 0: 85, 1: 77, 7: 75, 10: 75, 11: 72, 6: 68, 5: 67, 4: 63, 8: 60, 2: 58}
year column: {139: 13, 138: 13, 137: 13, 141: 13, 142: 13, 143: 13, 140: 13, 144: 13, 147: 13, 146: 13, 145: 13, 113: 13, 114: 13, 115: 13, 116: 13, 117: 13, 118: 13, 119: 13, 120: 13, 99: 13, 100: 13, 101: 13, 110: 13, 112: 13, 111: 13, 98: 13, 97: 13, 153: 13, 150: 13, 151: 13, 148: 13, 149: 13, 152: 13, 135: 13, 132: 13, 133: 13, 134: 13, 136: 13, 108: 12, 96: 12, 94: 12, 126: 12, 125: 12, 129: 12, 127: 12, 130: 12, 128: 12, 124: 12, 131: 12, 102: 12, 121: 12, 109: 12, 123: 12, 122: 12, 95: 12, 154: 11, 105: 11, 106: 11, 92: 11, 103: 11, 93: 11, 104: 11, 107: 11, 90: 10, 88: 10, 89: 10, 91: 10, 87: 9, 83: 8, 85: 8, 84: 8, 86: 8, 82: 7, 81: 7, 80: 7, 79: 5, 75: 4, 72: 4, 76: 4, 62: 4, 61: 4, 67: 4, 63: 4, 74: 4, 73: 4, 69: 4, 71: 4, 78: 4, 77: 4, 70: 4, 68: 4, 66: 3, 65: 3, 64: 3, 22: 2, 17: 2, 10: 2, 11: 2, 21: 2, 13: 2, 14: 2, 15: 2, 16: 2, 19: 2, 18: 2, 20: 2, 12: 2, 24: 2, 23: 2, 47: 2, 48: 2, 49: 2, 50: 2, 51: 2, 52: 2, 53: 2, 54: 2, 55: 2, 40: 2, 44: 2, 43: 2, 42: 2, 41: 2, 57: 2, 58: 2, 59: 2, 56: 2, 60: 2, 45: 2, 46: 2, 8: 1, 5: 1, 4: 1, 3: 1, 2: 1, 1: 1, 0: 1, 7: 1, 6: 1, 28: 1, 27: 1, 26: 1, 25: 1, 9: 1, 38: 1, 39: 1, 37: 1, 30: 1, 31: 1, 29: 1, 32: 1, 33: 1, 34: 1, 35: 1, 36: 1}
systemic_crisis column: {0: 977, 1: 82}
exch_usd column: {0: 53, 492: 21, 29: 15, 254: 12, 222: 9, 12: 9, 208: 9, 236: 8, 81: 8, 374: 7, 734: 7, 243: 7, 287: 6, 71: 6, 264: 6, 251: 6, 372: 6, 207: 5, 247: 5, 85: 5, 237: 5, 176: 5, 225: 5, 438: 5, 286: 4, 185: 4, 491: 4, 198: 4, 104: 3, 179: 3, 329: 3, 197: 3, 177: 3, 240: 3, 667: 3, 112: 3, 96: 3, 183: 3, 738: 3, 262: 3, 365: 3, 697: 2, 182: 2, 136: 2, 139: 2, 168: 2, 439: 2, 157: 2, 296: 2, 83: 2, 60: 2, 310: 2, 164: 2, 64: 2, 448: 2, 440: 2, 574: 2, 175: 2, 214: 2, 216: 2, 173: 2, 155: 2, 224: 2, 416: 2, 66: 2, 242: 2, 65: 2, 421: 2, 359: 2, 82: 2, 94: 2, 93: 2, 113: 2, 722: 2, 73: 2, 109: 2, 418: 2, 6: 2, 7: 2, 404: 2, 323: 2, 26: 2, 84: 2, 52: 2, 436: 1, 450: 1, 423: 1, 430: 1, 437: 1, 486: 1, 506: 1, 548: 1, 571: 1, 579: 1, 581: 1, 602: 1, 607: 1, 612: 1, 613: 1, 615: 1, 621: 1, 634: 1, 641: 1, 647: 1, 626: 1, 627: 1, 630: 1, 623: 1, 619: 1, 624: 1, 628: 1, 631: 1, 636: 1, 643: 1, 644: 1, 655: 1, 59: 1, 79: 1, 62: 1, 61: 1, 68: 1, 86: 1, 87: 1, 63: 1, 67: 1, 69: 1, 78: 1, 72: 1, 74: 1, 80: 1, 77: 1, 75: 1, 70: 1, 76: 1, 88: 1, 89: 1, 90: 1, 95: 1, 126: 1, 188: 1, 228: 1, 284: 1, 462: 1, 563: 1, 599: 1, 614: 1, 646: 1, 652: 1, 650: 1, 648: 1, 632: 1, 633: 1, 657: 1, 658: 1, 659: 1, 660: 1, 661: 1, 663: 1, 684: 1, 702: 1, 704: 1, 701: 1, 698: 1, 700: 1, 699: 1, 707: 1, 703: 1, 706: 1, 721: 1, 719: 1, 713: 1, 710: 1, 693: 1, 689: 1, 690: 1, 708: 1, 692: 1, 683: 1, 681: 1, 691: 1, 723: 1, 733: 1, 742: 1, 748: 1, 739: 1, 732: 1, 716: 1, 728: 1, 724: 1, 711: 1, 712: 1, 718: 1, 726: 1, 760: 1, 751: 1, 758: 1, 766: 1, 764: 1, 769: 1, 770: 1, 771: 1, 768: 1, 757: 1, 749: 1, 763: 1, 755: 1, 743: 1, 746: 1, 745: 1, 752: 1, 756: 1, 754: 1, 747: 1, 762: 1, 714: 1, 709: 1, 695: 1, 688: 1, 686: 1, 705: 1, 694: 1, 696: 1, 682: 1, 687: 1, 725: 1, 736: 1, 744: 1, 750: 1, 741: 1, 731: 1, 720: 1, 730: 1, 729: 1, 717: 1, 715: 1, 727: 1, 761: 1, 753: 1, 759: 1, 767: 1, 765: 1, 152: 1, 160: 1, 165: 1, 156: 1, 162: 1, 148: 1, 151: 1, 163: 1, 178: 1, 171: 1, 180: 1, 172: 1, 170: 1, 159: 1, 167: 1, 166: 1, 149: 1, 158: 1, 169: 1, 184: 1, 181: 1, 174: 1, 204: 1, 192: 1, 227: 1, 229: 1, 220: 1, 215: 1, 219: 1, 209: 1, 186: 1, 230: 1, 232: 1, 147: 1, 161: 1, 150: 1, 211: 1, 223: 1, 320: 1, 347: 1, 361: 1, 362: 1, 364: 1, 367: 1, 366: 1, 369: 1, 377: 1, 403: 1, 475: 1, 474: 1, 468: 1, 467: 1, 456: 1, 457: 1, 455: 1, 470: 1, 473: 1, 478: 1, 489: 1, 493: 1, 488: 1, 516: 1, 505: 1, 494: 1, 495: 1, 497: 1, 540: 1, 550: 1, 552: 1, 559: 1, 561: 1, 560: 1, 562: 1, 568: 1, 572: 1, 580: 1, 586: 1, 601: 1, 620: 1, 603: 1, 611: 1, 608: 1, 618: 1, 616: 1, 629: 1, 642: 1, 645: 1, 638: 1, 637: 1, 639: 1, 625: 1, 622: 1, 617: 1, 640: 1, 635: 1, 649: 1, 651: 1, 653: 1, 654: 1, 656: 1, 429: 1, 414: 1, 413: 1, 427: 1, 426: 1, 411: 1, 420: 1, 415: 1, 422: 1, 425: 1, 417: 1, 424: 1, 459: 1, 463: 1, 460: 1, 461: 1, 452: 1, 466: 1, 469: 1, 465: 1, 482: 1, 484: 1, 480: 1, 472: 1, 499: 1, 503: 1, 541: 1, 544: 1, 549: 1, 558: 1, 554: 1, 551: 1, 547: 1, 553: 1, 557: 1, 555: 1, 556: 1, 564: 1, 569: 1, 566: 1, 565: 1, 567: 1, 578: 1, 582: 1, 583: 1, 585: 1, 594: 1, 589: 1, 584: 1, 587: 1, 596: 1, 600: 1, 588: 1, 598: 1, 592: 1, 593: 1, 590: 1, 595: 1, 591: 1, 597: 1, 142: 1, 269: 1, 268: 1, 135: 1, 349: 1, 15: 1, 375: 1, 395: 1, 434: 1, 382: 1, 442: 1, 133: 1, 441: 1, 443: 1, 445: 1, 446: 1, 447: 1, 444: 1, 419: 1, 406: 1, 384: 1, 391: 1, 383: 1, 394: 1, 396: 1, 385: 1, 379: 1, 397: 1, 453: 1, 477: 1, 508: 1, 534: 1, 535: 1, 524: 1, 502: 1, 514: 1, 510: 1, 507: 1, 512: 1, 530: 1, 536: 1, 528: 1, 520: 1, 526: 1, 537: 1, 532: 1, 538: 1, 543: 1, 545: 1, 539: 1, 525: 1, 515: 1, 531: 1, 519: 1, 501: 1, 509: 1, 504: 1, 517: 1, 522: 1, 518: 1, 513: 1, 527: 1, 278: 1, 273: 1, 271: 1, 274: 1, 277: 1, 276: 1, 270: 1, 265: 1, 275: 1, 281: 1, 295: 1, 299: 1, 317: 1, 360: 1, 390: 1, 454: 1, 500: 1, 529: 1, 570: 1, 573: 1, 577: 1, 576: 1, 575: 1, 134: 1, 662: 1, 664: 1, 665: 1, 668: 1, 674: 1, 672: 1, 670: 1, 669: 1, 666: 1, 673: 1, 675: 1, 676: 1, 680: 1, 679: 1, 677: 1, 678: 1, 205: 1, 193: 1, 195: 1, 194: 1, 137: 1, 201: 1, 191: 1, 200: 1, 196: 1, 199: 1, 146: 1, 206: 1, 212: 1, 143: 1, 213: 1, 226: 1, 221: 1, 218: 1, 132: 1, 203: 1, 202: 1, 141: 1, 210: 1, 154: 1, 153: 1, 190: 1, 189: 1, 187: 1, 217: 1, 140: 1, 255: 1, 233: 1, 231: 1, 235: 1, 261: 1, 241: 1, 238: 1, 239: 1, 256: 1, 244: 1, 245: 1, 324: 1, 288: 1, 289: 1, 291: 1, 290: 1, 283: 1, 293: 1, 279: 1, 280: 1, 282: 1, 305: 1, 306: 1, 307: 1, 300: 1, 294: 1, 313: 1, 319: 1, 328: 1, 346: 1, 353: 1, 348: 1, 345: 1, 350: 1, 352: 1, 354: 1, 356: 1, 358: 1, 368: 1, 373: 1, 376: 1, 412: 1, 432: 1, 471: 1, 476: 1, 498: 1, 546: 1, 523: 1, 485: 1, 464: 1, 479: 1, 490: 1, 487: 1, 533: 1, 496: 1, 483: 1, 511: 1, 521: 1, 542: 1, 605: 1, 604: 1, 671: 1, 606: 1, 610: 1, 609: 1, 355: 1, 685: 1, 370: 1, 735: 1, 250: 1, 371: 1, 393: 1, 260: 1, 259: 1, 246: 1, 252: 1, 258: 1, 266: 1, 253: 1, 257: 1, 248: 1, 249: 1, 263: 1, 272: 1, 292: 1, 304: 1, 297: 1, 302: 1, 298: 1, 308: 1, 309: 1, 301: 1, 303: 1, 311: 1, 318: 1, 315: 1, 312: 1, 316: 1, 322: 1, 321: 1, 330: 1, 337: 1, 340: 1, 335: 1, 326: 1, 325: 1, 336: 1, 332: 1, 327: 1, 333: 1, 334: 1, 338: 1, 341: 1, 342: 1, 343: 1, 344: 1, 433: 1, 435: 1, 91: 1, 92: 1, 108: 1, 106: 1, 114: 1, 99: 1, 98: 1, 410: 1, 405: 1, 100: 1, 105: 1, 110: 1, 103: 1, 101: 1, 111: 1, 392: 1, 97: 1, 102: 1, 107: 1, 387: 1, 389: 1, 118: 1, 115: 1, 117: 1, 116: 1, 119: 1, 120: 1, 121: 1, 122: 1, 124: 1, 125: 1, 129: 1, 127: 1, 128: 1, 130: 1, 131: 1, 145: 1, 234: 1, 267: 1, 285: 1, 314: 1, 331: 1, 339: 1, 351: 1, 357: 1, 402: 1, 378: 1, 400: 1, 407: 1, 363: 1, 401: 1, 381: 1, 431: 1, 408: 1, 428: 1, 449: 1, 451: 1, 458: 1, 481: 1, 11: 1, 9: 1, 10: 1, 398: 1, 388: 1, 39: 1, 17: 1, 1: 1, 3: 1, 4: 1, 5: 1, 2: 1, 8: 1, 13: 1, 25: 1, 380: 1, 32: 1, 386: 1, 28: 1, 30: 1, 27: 1, 31: 1, 23: 1, 22: 1, 16: 1, 14: 1, 19: 1, 18: 1, 21: 1, 399: 1, 24: 1, 20: 1, 33: 1, 34: 1, 35: 1, 36: 1, 38: 1, 138: 1, 37: 1, 40: 1, 41: 1, 42: 1, 43: 1, 44: 1, 45: 1, 46: 1, 47: 1, 48: 1, 49: 1, 50: 1, 51: 1, 409: 1, 53: 1, 54: 1, 55: 1, 56: 1, 57: 1, 58: 1, 123: 1, 737: 1, 740: 1, 144: 1}
domestic_debt_in_default column: {0: 1017, 1: 42}
sovereign_external_debt_default column: {0: 897, 1: 162}
gdp_weighted_default column: {0: 1029, 1: 7, 3: 6, 5: 6, 2: 6, 4: 5}
inflation_annual_cpi column: {128: 17, 242: 3, 103: 3, 584: 2, 397: 2, 256: 2, 890: 2, 714: 2, 618: 2, 491: 2, 172: 2, 606: 2, 528: 2, 577: 2, 86: 2, 277: 2, 804: 2, 298: 2, 442: 2, 362: 2, 570: 1, 547: 1, 628: 1, 946: 1, 784: 1, 593: 1, 563: 1, 210: 1, 354: 1, 819: 1, 62: 1, 743: 1, 60: 1, 2: 1, 83: 1, 941: 1, 88: 1, 7: 1, 387: 1, 781: 1, 234: 1, 311: 1, 771: 1, 673: 1, 473: 1, 313: 1, 904: 1, 281: 1, 368: 1, 536: 1, 441: 1, 663: 1, 659: 1, 765: 1, 863: 1, 752: 1, 687: 1, 829: 1, 686: 1, 830: 1, 561: 1, 615: 1, 545: 1, 715: 1, 815: 1, 508: 1, 514: 1, 669: 1, 675: 1, 927: 1, 92: 1, 939: 1, 945: 1, 875: 1, 457: 1, 279: 1, 133: 1, 405: 1, 197: 1, 413: 1, 395: 1, 194: 1, 253: 1, 369: 1, 447: 1, 497: 1, 391: 1, 430: 1, 661: 1, 345: 1, 312: 1, 944: 1, 967: 1, 987: 1, 1002: 1, 1: 1, 35: 1, 4: 1, 23: 1, 47: 1, 45: 1, 76: 1, 252: 1, 351: 1, 478: 1, 98: 1, 239: 1, 810: 1, 861: 1, 867: 1, 813: 1, 611: 1, 464: 1, 450: 1, 802: 1, 6: 1, 30: 1, 334: 1, 55: 1, 336: 1, 175: 1, 237: 1, 236: 1, 513: 1, 621: 1, 501: 1, 848: 1, 845: 1, 933: 1, 940: 1, 993: 1, 988: 1, 973: 1, 997: 1, 971: 1, 994: 1, 1011: 1, 1017: 1, 1015: 1, 1018: 1, 1019: 1, 1009: 1, 998: 1, 1010: 1, 1012: 1, 1005: 1, 999: 1, 996: 1, 965: 1, 907: 1, 797: 1, 770: 1, 774: 1, 806: 1, 825: 1, 801: 1, 711: 1, 652: 1, 595: 1, 572: 1, 783: 1, 380: 1, 732: 1, 559: 1, 372: 1, 701: 1, 679: 1, 294: 1, 227: 1, 445: 1, 138: 1, 376: 1, 934: 1, 25: 1, 487: 1, 684: 1, 851: 1, 717: 1, 739: 1, 753: 1, 672: 1, 796: 1, 831: 1, 795: 1, 828: 1, 280: 1, 716: 1, 260: 1, 37: 1, 59: 1, 142: 1, 124: 1, 71: 1, 107: 1, 69: 1, 921: 1, 881: 1, 374: 1, 208: 1, 81: 1, 91: 1, 339: 1, 384: 1, 251: 1, 420: 1, 77: 1, 308: 1, 567: 1, 164: 1, 674: 1, 358: 1, 200: 1, 185: 1, 510: 1, 557: 1, 756: 1, 856: 1, 75: 1, 433: 1, 792: 1, 897: 1, 548: 1, 80: 1, 824: 1, 125: 1, 650: 1, 65: 1, 216: 1, 436: 1, 295: 1, 610: 1, 272: 1, 623: 1, 97: 1, 184: 1, 789: 1, 872: 1, 721: 1, 788: 1, 920: 1, 852: 1, 901: 1, 653: 1, 648: 1, 599: 1, 511: 1, 415: 1, 214: 1, 574: 1, 581: 1, 170: 1, 108: 1, 206: 1, 407: 1, 245: 1, 928: 1, 818: 1, 286: 1, 544: 1, 470: 1, 162: 1, 119: 1, 421: 1, 328: 1, 349: 1, 199: 1, 388: 1, 266: 1, 229: 1, 546: 1, 174: 1, 219: 1, 428: 1, 190: 1, 278: 1, 136: 1, 519: 1, 526: 1, 517: 1, 522: 1, 524: 1, 520: 1, 518: 1, 523: 1, 521: 1, 515: 1, 525: 1, 790: 1, 53: 1, 54: 1, 204: 1, 26: 1, 19: 1, 118: 1, 114: 1, 719: 1, 217: 1, 12: 1, 409: 1, 78: 1, 115: 1, 40: 1, 365: 1, 72: 1, 42: 1, 14: 1, 620: 1, 706: 1, 233: 1, 10: 1, 50: 1, 43: 1, 688: 1, 302: 1, 820: 1, 41: 1, 598: 1, 130: 1, 113: 1, 32: 1, 73: 1, 841: 1, 682: 1, 191: 1, 658: 1, 183: 1, 16: 1, 189: 1, 542: 1, 750: 1, 95: 1, 8: 1, 882: 1, 954: 1, 870: 1, 767: 1, 892: 1, 0: 1, 15: 1, 18: 1, 594: 1, 490: 1, 17: 1, 27: 1, 429: 1, 64: 1, 38: 1, 48: 1, 20: 1, 22: 1, 915: 1, 488: 1, 34: 1, 100: 1, 751: 1, 90: 1, 713: 1, 917: 1, 960: 1, 865: 1, 748: 1, 244: 1, 66: 1, 146: 1, 639: 1, 603: 1, 21: 1, 104: 1, 70: 1, 394: 1, 344: 1, 93: 1, 145: 1, 148: 1, 182: 1, 52: 1, 240: 1, 614: 1, 793: 1, 566: 1, 131: 1, 137: 1, 370: 1, 350: 1, 317: 1, 262: 1, 496: 1, 722: 1, 695: 1, 712: 1, 758: 1, 746: 1, 696: 1, 833: 1, 850: 1, 862: 1, 766: 1, 914: 1, 925: 1, 837: 1, 888: 1, 898: 1, 832: 1, 896: 1, 737: 1, 667: 1, 677: 1, 589: 1, 535: 1, 461: 1, 377: 1, 303: 1, 263: 1, 340: 1, 625: 1, 655: 1, 406: 1, 733: 1, 761: 1, 857: 1, 760: 1, 738: 1, 644: 1, 580: 1, 704: 1, 676: 1, 359: 1, 640: 1, 731: 1, 552: 1, 326: 1, 425: 1, 549: 1, 218: 1, 282: 1, 157: 1, 155: 1, 274: 1, 292: 1, 122: 1, 500: 1, 378: 1, 139: 1, 143: 1, 126: 1, 222: 1, 485: 1, 431: 1, 782: 1, 860: 1, 884: 1, 683: 1, 869: 1, 840: 1, 624: 1, 811: 1, 809: 1, 757: 1, 893: 1, 749: 1, 710: 1, 791: 1, 443: 1, 604: 1, 742: 1, 880: 1, 932: 1, 968: 1, 938: 1, 203: 1, 657: 1, 764: 1, 569: 1, 499: 1, 697: 1, 507: 1, 247: 1, 527: 1, 635: 1, 613: 1, 530: 1, 414: 1, 836: 1, 720: 1, 417: 1, 816: 1, 678: 1, 493: 1, 579: 1, 24: 1, 947: 1, 176: 1, 452: 1, 740: 1, 232: 1, 109: 1, 166: 1, 121: 1, 307: 1, 105: 1, 141: 1, 110: 1, 223: 1, 111: 1, 153: 1, 215: 1, 221: 1, 228: 1, 320: 1, 316: 1, 471: 1, 319: 1, 129: 1, 225: 1, 483: 1, 894: 1, 913: 1, 838: 1, 727: 1, 692: 1, 668: 1, 911: 1, 949: 1, 930: 1, 798: 1, 601: 1, 481: 1, 634: 1, 419: 1, 147: 1, 364: 1, 803: 1, 725: 1, 785: 1, 305: 1, 839: 1, 597: 1, 935: 1, 558: 1, 573: 1, 571: 1, 969: 1, 408: 1, 474: 1, 551: 1, 393: 1, 439: 1, 455: 1, 662: 1, 656: 1, 690: 1, 273: 1, 315: 1, 556: 1, 451: 1, 400: 1, 379: 1, 924: 1, 948: 1, 957: 1, 937: 1, 951: 1, 879: 1, 980: 1, 984: 1, 959: 1, 908: 1, 209: 1, 910: 1, 466: 1, 94: 1, 269: 1, 509: 1, 492: 1, 254: 1, 422: 1, 79: 1, 248: 1, 250: 1, 475: 1, 494: 1, 410: 1, 267: 1, 123: 1, 96: 1, 180: 1, 212: 1, 230: 1, 423: 1, 341: 1, 592: 1, 849: 1, 587: 1, 734: 1, 729: 1, 689: 1, 645: 1, 681: 1, 775: 1, 718: 1, 539: 1, 772: 1, 609: 1, 651: 1, 285: 1, 258: 1, 335: 1, 665: 1, 495: 1, 465: 1, 463: 1, 533: 1, 321: 1, 177: 1, 293: 1, 144: 1, 231: 1, 140: 1, 299: 1, 181: 1, 201: 1, 169: 1, 347: 1, 238: 1, 390: 1, 168: 1, 171: 1, 161: 1, 188: 1, 224: 1, 135: 1, 330: 1, 537: 1, 576: 1, 202: 1, 63: 1, 440: 1, 418: 1, 540: 1, 310: 1, 99: 1, 165: 1, 434: 1, 626: 1, 51: 1, 291: 1, 735: 1, 800: 1, 843: 1, 127: 1, 759: 1, 745: 1, 958: 1, 874: 1, 906: 1, 847: 1, 703: 1, 698: 1, 891: 1, 512: 1, 903: 1, 961: 1, 343: 1, 543: 1, 763: 1, 950: 1, 974: 1, 966: 1, 982: 1, 983: 1, 992: 1, 942: 1, 724: 1, 616: 1, 565: 1, 582: 1, 877: 1, 786: 1, 817: 1, 834: 1, 866: 1, 630: 1, 476: 1, 755: 1, 778: 1, 805: 1, 730: 1, 768: 1, 637: 1, 622: 1, 399: 1, 671: 1, 261: 1, 29: 1, 46: 1, 39: 1, 33: 1, 85: 1, 84: 1, 446: 1, 842: 1, 396: 1, 276: 1, 187: 1, 186: 1, 448: 1, 506: 1, 694: 1, 585: 1, 163: 1, 953: 1, 3: 1, 58: 1, 149: 1, 87: 1, 963: 1, 255: 1, 106: 1, 74: 1, 57: 1, 44: 1, 259: 1, 89: 1, 117: 1, 160: 1, 486: 1, 120: 1, 158: 1, 392: 1, 529: 1, 647: 1, 458: 1, 389: 1, 150: 1, 531: 1, 416: 1, 575: 1, 943: 1, 578: 1, 605: 1, 564: 1, 151: 1, 385: 1, 213: 1, 226: 1, 346: 1, 337: 1, 152: 1, 207: 1, 241: 1, 192: 1, 173: 1, 401: 1, 356: 1, 367: 1, 246: 1, 327: 1, 383: 1, 449: 1, 568: 1, 636: 1, 728: 1, 808: 1, 744: 1, 747: 1, 707: 1, 769: 1, 812: 1, 821: 1, 846: 1, 823: 1, 780: 1, 741: 1, 855: 1, 876: 1, 854: 1, 787: 1, 827: 1, 822: 1, 844: 1, 871: 1, 693: 1, 654: 1, 649: 1, 596: 1, 643: 1, 468: 1, 472: 1, 670: 1, 505: 1, 196: 1, 352: 1, 438: 1, 588: 1, 754: 1, 590: 1, 412: 1, 459: 1, 489: 1, 498: 1, 902: 1, 922: 1, 923: 1, 991: 1, 956: 1, 807: 1, 975: 1, 986: 1, 989: 1, 403: 1, 357: 1, 835: 1, 586: 1, 112: 1, 404: 1, 444: 1, 479: 1, 469: 1, 28: 1, 220: 1, 82: 1, 502: 1, 167: 1, 516: 1, 482: 1, 432: 1, 301: 1, 268: 1, 300: 1, 205: 1, 411: 1, 289: 1, 503: 1, 437: 1, 702: 1, 348: 1, 629: 1, 435: 1, 641: 1, 700: 1, 660: 1, 664: 1, 642: 1, 602: 1, 534: 1, 631: 1, 591: 1, 608: 1, 554: 1, 607: 1, 480: 1, 398: 1, 477: 1, 541: 1, 375: 1, 363: 1, 329: 1, 296: 1, 297: 1, 235: 1, 288: 1, 290: 1, 366: 1, 198: 1, 402: 1, 353: 1, 453: 1, 360: 1, 424: 1, 361: 1, 462: 1, 504: 1, 456: 1, 306: 1, 990: 1, 287: 1, 617: 1, 264: 1, 985: 1, 249: 1, 427: 1, 550: 1, 386: 1, 371: 1, 912: 1, 331: 1, 338: 1, 179: 1, 355: 1, 132: 1, 193: 1, 116: 1, 324: 1, 627: 1, 708: 1, 460: 1, 726: 1, 275: 1, 555: 1, 553: 1, 619: 1, 705: 1, 878: 1, 885: 1, 853: 1, 685: 1, 762: 1, 814: 1, 776: 1, 883: 1, 886: 1, 955: 1, 978: 1, 972: 1, 976: 1, 1003: 1, 1000: 1, 995: 1, 1006: 1, 1007: 1, 977: 1, 952: 1, 964: 1, 918: 1, 919: 1, 931: 1, 929: 1, 899: 1, 905: 1, 900: 1, 868: 1, 873: 1, 666: 1, 723: 1, 773: 1, 799: 1, 638: 1, 646: 1, 560: 1, 612: 1, 5: 1, 11: 1, 56: 1, 156: 1, 154: 1, 49: 1, 36: 1, 61: 1, 67: 1, 102: 1, 101: 1, 538: 1, 68: 1, 159: 1, 322: 1, 381: 1, 484: 1, 532: 1, 323: 1, 284: 1, 467: 1, 314: 1, 680: 1, 382: 1, 583: 1, 13: 1, 211: 1, 426: 1, 318: 1, 283: 1, 265: 1, 309: 1, 178: 1, 271: 1, 270: 1, 333: 1, 257: 1, 195: 1, 134: 1, 243: 1, 325: 1, 304: 1, 332: 1, 562: 1, 699: 1, 736: 1, 709: 1, 632: 1, 779: 1, 691: 1, 794: 1, 909: 1, 889: 1, 633: 1, 826: 1, 777: 1, 600: 1, 9: 1, 864: 1, 916: 1, 962: 1, 936: 1, 895: 1, 926: 1, 859: 1, 887: 1, 970: 1, 981: 1, 979: 1, 1001: 1, 1008: 1, 1014: 1, 1004: 1, 1013: 1, 1016: 1, 1020: 1, 1021: 1, 31: 1, 342: 1, 454: 1, 373: 1, 858: 1}
independence column: {1: 822, 0: 237}
currency_crises column: {0: 923, 1: 132, 2: 4}
inflation_crises column: {0: 922, 1: 137}
banking_crisis column: {1: 965, 0: 94}

In [162]:
#df['banking_crisis'] colonne prédite
df['banking_crisis'].value_counts().to_dict() 
#equilibrage is only concerned with binary columns where there is an imbalance between number of zeros and number of ones

{0: 965, 1: 94}

In [167]:
from imblearn.over_sampling import SMOTE #no need to make research about the details of SMOTE, understanding the concept only is enough 

#splitting colonne predite (y) from other cols (x)
X=df.drop(columns=['banking_crisis'])
y=df['banking_crisis'] #colonne prédite/ target

#initialize & apply the SMOTE algorithm
smote = SMOTE(random_state=42)
X_resampled_smote, y_resampled_smote = smote.fit_resample(X, y) #we will put the results of fit resample in two variables that are balanced

#concatenate & create the new balanced DataFrame
df_resampled = pd.concat([X_resampled_smote, y_resampled_smote], axis=1)   # axis=1  ==> column level: concat them au niveau des colonnes
df = df_resampled

#this code always stays the same (change name of columns only)

In [168]:
df['banking_crisis'].value_counts().to_dict()

{0: 965, 1: 965}

## Data Exploration

In [83]:
df.columns

Index(['country_number', 'country_code', 'country', 'year', 'systemic_crisis',
       'exch_usd', 'domestic_debt_in_default',
       'sovereign_external_debt_default', 'gdp_weighted_default',
       'inflation_annual_cpi', 'independence', 'currency_crises',
       'inflation_crises', 'banking_crisis'],
      dtype='object')

In [84]:
df.head(5)

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,0,0,0,crisis
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,0,0,0,no_crisis
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,0,0,0,no_crisis
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,0,0,0,no_crisis
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,0,0,0,no_crisis

In [85]:
df.tail()

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
1054,70,ZWE,Zimbabwe,2009,1,354.8,1,1,0.0,-7.670,1,1,0,crisis
1055,70,ZWE,Zimbabwe,2010,0,378.2,1,1,0.0,3.217,1,0,0,no_crisis
1056,70,ZWE,Zimbabwe,2011,0,361.9,1,1,0.0,4.920,1,0,0,no_crisis
1057,70,ZWE,Zimbabwe,2012,0,361.9,1,1,0.0,3.720,1,0,0,no_crisis
1058,70,ZWE,Zimbabwe,2013,0,361.9,1,1,0.0,1.632,1,0,0,no_crisis

In [86]:
#number of columns
len(df.columns)

14

In [87]:
df.info() #displays type of cols(dtype), rangeIndex,nombre total de colonnes, names of cols, number of non-null values,memory usage
#type object=string
#preferably all cols are of the same type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country_number                   1059 non-null   int64
 1   country_code                     1059 non-null   object
 2   country                          1059 non-null   object
 3   year                             1059 non-null   int64
 4   systemic_crisis                  1059 non-null   int64
 5   exch_usd                         1059 non-null   float64
 6   domestic_debt_in_default         1059 non-null   int64
 7   sovereign_external_debt_default  1059 non-null   int64
 8   gdp_weighted_default             1059 non-null   float64
 9   inflation_annual_cpi             1059 non-null   float64
 10  independence                     1059 non-null   int64
 11  currency_crises                  1059 non-null   int64
 12  inflation_crises                 1059 non-null   int64
 13  banking_crisis                   1059 non-null   object
dtypes: float64(3), int64(8), object(3)
memory usage: 116.0+ KB

In [88]:
df.shape #range index (numb of rows) & number of columns in a tupe

(1059, 14)

In [89]:
df.size #total numbe rof elements in the whole df (product of shape:1059*14)

14826

In [90]:
n_rows=df.shape[0] #to access the number of rows in the tuple given by shape
n_rows

1059

In [91]:
n_col=df.shape[1]
n_col

14

In [92]:
df.describe()

,country_number,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises
count,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1.059000e+03,1059.000000,1059.000000,1059.000000
mean,35.613787,1967.767705,0.077432,43.140831,0.039660,0.152975,0.006402,2.084889e+04,0.776204,0.132200,0.129367
std,23.692402,33.530632,0.267401,111.475380,0.195251,0.360133,0.043572,6.757274e+05,0.416984,0.349847,0.335765
min,1.000000,1860.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.850214e+01,0.000000,0.000000,0.000000
25%,15.000000,1951.000000,0.000000,0.195350,0.000000,0.000000,0.000000,2.086162e+00,1.000000,0.000000,0.000000
50%,38.000000,1973.000000,0.000000,0.868400,0.000000,0.000000,0.000000,5.762330e+00,1.000000,0.000000,0.000000
75%,56.000000,1994.000000,0.000000,8.462750,0.000000,0.000000,0.000000,1.164405e+01,1.000000,0.000000,0.000000
max,70.000000,2014.000000,1.000000,744.306139,1.000000,1.000000,0.400000,2.198970e+07,1.000000,2.000000,1.000000

In [93]:
df.describe(include='all') #ads unique, top, freq of categorical variables (cols)=of type object

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
count,1059.000000,1059,1059,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1.059000e+03,1059.000000,1059.000000,1059.000000,1059
unique,NaN,13,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,EGY,Egypt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no_crisis
freq,NaN,155,155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,965
mean,35.613787,NaN,NaN,1967.767705,0.077432,43.140831,0.039660,0.152975,0.006402,2.084889e+04,0.776204,0.132200,0.129367,NaN
std,23.692402,NaN,NaN,33.530632,0.267401,111.475380,0.195251,0.360133,0.043572,6.757274e+05,0.416984,0.349847,0.335765,NaN
min,1.000000,NaN,NaN,1860.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.850214e+01,0.000000,0.000000,0.000000,NaN
25%,15.000000,NaN,NaN,1951.000000,0.000000,0.195350,0.000000,0.000000,0.000000,2.086162e+00,1.000000,0.000000,0.000000,NaN
50%,38.000000,NaN,NaN,1973.000000,0.000000,0.868400,0.000000,0.000000,0.000000,5.762330e+00,1.000000,0.000000,0.000000,NaN
75%,56.000000,NaN,NaN,1994.000000,0.000000,8.462750,0.000000,0.000000,0.000000,1.164405e+01,1.000000,0.000000,0.000000,NaN
max,70.000000,NaN,NaN,2014.000000,1.000000,744.306139,1.000000,1.000000,0.400000,2.198970e+07,1.000000,2.000000,1.000000,NaN

In [94]:
#corrupted values: problem in the type due to a charachter

In [95]:
df.columns #to get the cols names in a list, ordered

Index(['country_number', 'country_code', 'country', 'year', 'systemic_crisis',
       'exch_usd', 'domestic_debt_in_default',
       'sovereign_external_debt_default', 'gdp_weighted_default',
       'inflation_annual_cpi', 'independence', 'currency_crises',
       'inflation_crises', 'banking_crisis'],
      dtype='object')

In [96]:
les_colonnes_réelles = df.select_dtypes(include=['float64']) #this function selects from the dtype, it will filter using include 
les_colonnes_réelles

        exch_usd  gdp_weighted_default  inflation_annual_cpi
0       0.052264                   0.0              3.441456
1       0.052798                   0.0             14.149140
2       0.052274                   0.0             -3.718593
3       0.051680                   0.0             11.203897
4       0.051308                   0.0             -3.848561
...          ...                   ...                   ...
1054  354.800000                   0.0             -7.670000
1055  378.200000                   0.0              3.217000
1056  361.900000                   0.0              4.920000
1057  361.900000                   0.0              3.720000
1058  361.900000                   0.0              1.632000

[1059 rows x 3 columns]

In [97]:
les_colonnes_entieres= df.select_dtypes(include=['int'])
les_colonnes_entieres

,country_number,year,systemic_crisis,domestic_debt_in_default,sovereign_external_debt_default,independence,currency_crises,inflation_crises
0,1,1870,1,0,0,0,0,0
1,1,1871,0,0,0,0,0,0
2,1,1872,0,0,0,0,0,0
3,1,1873,0,0,0,0,0,0
4,1,1874,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
1054,70,2009,1,1,1,1,1,0
1055,70,2010,0,1,1,1,0,0
1056,70,2011,0,1,1,1,0,0
1057,70,2012,0,1,1,1,0,0
1058,70,2013,0,1,1,1,0,0

In [98]:
les_colonnes_categoric=df.select_dtypes(include=['object'])
les_colonnes_categoric

     country_code   country banking_crisis
0             DZA   Algeria         crisis
1             DZA   Algeria      no_crisis
2             DZA   Algeria      no_crisis
3             DZA   Algeria      no_crisis
4             DZA   Algeria      no_crisis
...           ...       ...            ...
1054          ZWE  Zimbabwe         crisis
1055          ZWE  Zimbabwe      no_crisis
1056          ZWE  Zimbabwe      no_crisis
1057          ZWE  Zimbabwe      no_crisis
1058          ZWE  Zimbabwe      no_crisis

[1059 rows x 3 columns]

In [99]:
les_colonnes_numeric=df.select_dtypes(include=['number']) #or exclude objects (gives bool& numerical), number can be in '' or without
les_colonnes_numeric

,country_number,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises
0,1,1870,1,0.052264,0,0,0.0,3.441456,0,0,0
1,1,1871,0,0.052798,0,0,0.0,14.149140,0,0,0
2,1,1872,0,0.052274,0,0,0.0,-3.718593,0,0,0
3,1,1873,0,0.051680,0,0,0.0,11.203897,0,0,0
4,1,1874,0,0.051308,0,0,0.0,-3.848561,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1054,70,2009,1,354.800000,1,1,0.0,-7.670000,1,1,0
1055,70,2010,0,378.200000,1,1,0.0,3.217000,1,0,0
1056,70,2011,0,361.900000,1,1,0.0,4.920000,1,0,0
1057,70,2012,0,361.900000,1,1,0.0,3.720000,1,0,0
1058,70,2013,0,361.900000,1,1,0.0,1.632000,1,0,0

In [100]:
les_colonnes_numeric=df.select_dtypes(exclude=['object'])
les_colonnes_numeric

,country_number,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises
0,1,1870,1,0.052264,0,0,0.0,3.441456,0,0,0
1,1,1871,0,0.052798,0,0,0.0,14.149140,0,0,0
2,1,1872,0,0.052274,0,0,0.0,-3.718593,0,0,0
3,1,1873,0,0.051680,0,0,0.0,11.203897,0,0,0
4,1,1874,0,0.051308,0,0,0.0,-3.848561,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1054,70,2009,1,354.800000,1,1,0.0,-7.670000,1,1,0
1055,70,2010,0,378.200000,1,1,0.0,3.217000,1,0,0
1056,70,2011,0,361.900000,1,1,0.0,4.920000,1,0,0
1057,70,2012,0,361.900000,1,1,0.0,3.720000,1,0,0
1058,70,2013,0,361.900000,1,1,0.0,1.632000,1,0,0

In [101]:
les_colonnes_datetime=df.select_dtypes(include=[np.datetime64])
les_colonnes_datetime

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1059 rows x 0 columns]

## Type Conversion

In [102]:
for col in ['country_number','year']: #for loop taaml traitement multiple
    df[col]=df[col].astype(float) #as type transforms the type

In [103]:
df.dtypes

country_number                     float64
country_code                        object
country                             object
year                               float64
systemic_crisis                      int64
exch_usd                           float64
domestic_debt_in_default             int64
sovereign_external_debt_default      int64
gdp_weighted_default               float64
inflation_annual_cpi               float64
independence                         int64
currency_crises                      int64
inflation_crises                     int64
banking_crisis                      object
dtype: object

In [104]:
df['country_number']=df['country_number'].astype(float) #we can do traitement without for if we have very few cols to transform

In [105]:
df.dtypes

country_number                     float64
country_code                        object
country                             object
year                               float64
systemic_crisis                      int64
exch_usd                           float64
domestic_debt_in_default             int64
sovereign_external_debt_default      int64
gdp_weighted_default               float64
inflation_annual_cpi               float64
independence                         int64
currency_crises                      int64
inflation_crises                     int64
banking_crisis                      object
dtype: object

In [106]:
df['country_code'] #ykharj series, to filter by one specific column

0       DZA
1       DZA
2       DZA
3       DZA
4       DZA
       ...
1054    ZWE
1055    ZWE
1056    ZWE
1057    ZWE
1058    ZWE
Name: country_code, Length: 1059, dtype: object

In [107]:
df['banking_crisis']

0          crisis
1       no_crisis
2       no_crisis
3       no_crisis
4       no_crisis
          ...
1054       crisis
1055    no_crisis
1056    no_crisis
1057    no_crisis
1058    no_crisis
Name: banking_crisis, Length: 1059, dtype: object

In [108]:
for col in les_colonnes_numeric:
    df[col]=pd.to_numeric(df[col]) #tforci e type

In [109]:
df.dtypes

country_number                     float64
country_code                        object
country                             object
year                               float64
systemic_crisis                      int64
exch_usd                           float64
domestic_debt_in_default             int64
sovereign_external_debt_default      int64
gdp_weighted_default               float64
inflation_annual_cpi               float64
independence                         int64
currency_crises                      int64
inflation_crises                     int64
banking_crisis                      object
dtype: object

In [110]:
df['banking_crisis']=df['banking_crisis'].astype(bool) #we can replace bool by str or int

## Indexing, Slicing

In [111]:
df.columns #obligatoire to execute

Index(['country_number', 'country_code', 'country', 'year', 'systemic_crisis',
       'exch_usd', 'domestic_debt_in_default',
       'sovereign_external_debt_default', 'gdp_weighted_default',
       'inflation_annual_cpi', 'independence', 'currency_crises',
       'inflation_crises', 'banking_crisis'],
      dtype='object')

In [112]:
#slicing: with pandas
df[['year','country','inflation_crises']] #double crochet ky nheb nhez akthr men colonne

        year   country  inflation_crises
0     1870.0   Algeria                 0
1     1871.0   Algeria                 0
2     1872.0   Algeria                 0
3     1873.0   Algeria                 0
4     1874.0   Algeria                 0
...      ...       ...               ...
1054  2009.0  Zimbabwe                 0
1055  2010.0  Zimbabwe                 0
1056  2011.0  Zimbabwe                 0
1057  2012.0  Zimbabwe                 0
1058  2013.0  Zimbabwe                 0

[1059 rows x 3 columns]

In [113]:
#change order of columns, try to always create a new variable. I changed the order inside the crochets
new_order_df=df[['year', 'banking_crisis', 'country_number', 'country_code', 'country', 'systemic_crisis',
       'exch_usd', 'domestic_debt_in_default', 'independence',
       'sovereign_external_debt_default', 'gdp_weighted_default',
       'inflation_annual_cpi', 'currency_crises',
       'inflation_crises' ]]
new_order_df.head(10)

,year,banking_crisis,country_number,country_code,country,systemic_crisis,exch_usd,domestic_debt_in_default,independence,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,currency_crises,inflation_crises
0,1870.0,True,1.0,DZA,Algeria,1,0.052264,0,0,0,0.0,3.441456,0,0
1,1871.0,True,1.0,DZA,Algeria,0,0.052798,0,0,0,0.0,14.149140,0,0
2,1872.0,True,1.0,DZA,Algeria,0,0.052274,0,0,0,0.0,-3.718593,0,0
3,1873.0,True,1.0,DZA,Algeria,0,0.051680,0,0,0,0.0,11.203897,0,0
4,1874.0,True,1.0,DZA,Algeria,0,0.051308,0,0,0,0.0,-3.848561,0,0
5,1875.0,True,1.0,DZA,Algeria,0,0.051546,0,0,0,0.0,-20.924178,0,0
6,1876.0,True,1.0,DZA,Algeria,0,0.051867,0,0,0,0.0,-1.769547,0,0
7,1877.0,True,1.0,DZA,Algeria,0,0.051867,0,0,0,0.0,29.116045,0,1
8,1878.0,True,1.0,DZA,Algeria,0,0.051948,0,0,0,0.0,-1.492537,0,0
9,1879.0,True,1.0,DZA,Algeria,0,0.052029,0,0,0,0.0,-16.831357,0,0

In [114]:
#slicing, iloc: locates with index, i obligatoire (tekbel ken les is)
df.iloc[:,:]

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
0,1.0,DZA,Algeria,1870.0,1,0.052264,0,0,0.0,3.441456,0,0,0,True
1,1.0,DZA,Algeria,1871.0,0,0.052798,0,0,0.0,14.149140,0,0,0,True
2,1.0,DZA,Algeria,1872.0,0,0.052274,0,0,0.0,-3.718593,0,0,0,True
3,1.0,DZA,Algeria,1873.0,0,0.051680,0,0,0.0,11.203897,0,0,0,True
4,1.0,DZA,Algeria,1874.0,0,0.051308,0,0,0.0,-3.848561,0,0,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,70.0,ZWE,Zimbabwe,2009.0,1,354.800000,1,1,0.0,-7.670000,1,1,0,True
1055,70.0,ZWE,Zimbabwe,2010.0,0,378.200000,1,1,0.0,3.217000,1,0,0,True
1056,70.0,ZWE,Zimbabwe,2011.0,0,361.900000,1,1,0.0,4.920000,1,0,0,True
1057,70.0,ZWE,Zimbabwe,2012.0,0,361.900000,1,1,0.0,3.720000,1,0,0,True
1058,70.0,ZWE,Zimbabwe,2013.0,0,361.900000,1,1,0.0,1.632000,1,0,0,True

In [115]:
#all values in year and country only
df.iloc[:,2:4]

       country    year
0      Algeria  1870.0
1      Algeria  1871.0
2      Algeria  1872.0
3      Algeria  1873.0
4      Algeria  1874.0
...        ...     ...
1054  Zimbabwe  2009.0
1055  Zimbabwe  2010.0
1056  Zimbabwe  2011.0
1057  Zimbabwe  2012.0
1058  Zimbabwe  2013.0

[1059 rows x 2 columns]

In [116]:
#500 premieres ligne de la derniere colonne
df.iloc[0:501,-1]

0      True
1      True
2      True
3      True
4      True
       ...
496    True
497    True
498    True
499    True
500    True
Name: banking_crisis, Length: 501, dtype: bool

In [117]:
df.iloc[: , -2:] #-2 kbal lekhra

      inflation_crises  banking_crisis
0                    0            True
1                    0            True
2                    0            True
3                    0            True
4                    0            True
...                ...             ...
1054                 0            True
1055                 0            True
1056                 0            True
1057                 0            True
1058                 0            True

[1059 rows x 2 columns]

In [118]:
#banking crisis khaw
df.iloc[: , -1:] #dyma nkhalou deux pts baad nombre bch yokhrj df mch series (azyen)

      banking_crisis
0               True
1               True
2               True
3               True
4               True
...              ...
1054            True
1055            True
1056            True
1057            True
1058            True

[1059 rows x 1 columns]

In [119]:
# last 500 rows and 'gdp_weighted_default' & 'inflation_annual_cpi' columns
df.iloc[-500:,8:10]

      gdp_weighted_default  inflation_annual_cpi
559                    0.0                 5.391
560                    0.0                 6.414
561                    0.0                 3.931
562                    0.0                 4.703
563                    0.0                 4.921
...                    ...                   ...
1054                   0.0                -7.670
1055                   0.0                 3.217
1056                   0.0                 4.920
1057                   0.0                 3.720
1058                   0.0                 1.632

[500 rows x 2 columns]

In [120]:
df.iloc[:,[0,5,10]] #des indices spécifiques de colonnes et toutes les lignes

      country_number    exch_usd  independence
0                1.0    0.052264             0
1                1.0    0.052798             0
2                1.0    0.052274             0
3                1.0    0.051680             0
4                1.0    0.051308             0
...              ...         ...           ...
1054            70.0  354.800000             1
1055            70.0  378.200000             1
1056            70.0  361.900000             1
1057            70.0  361.900000             1
1058            70.0  361.900000             1

[1059 rows x 3 columns]

In [121]:
#slicing: locates without index. loc can take a single label (index:can be letter or int) or list/array of labels
#loc tekbel taaml filtrz b les conditions
df.loc[df['year'] >2000] #the indices will be random and not ordered
#search all and any functions to do more than one condition

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
71,1.0,DZA,Algeria,2001.0,0,77.8196,0,0,0.0,4.200,1,0,0,True
72,1.0,DZA,Algeria,2002.0,0,79.7234,0,0,0.0,1.430,1,0,0,True
73,1.0,DZA,Algeria,2003.0,0,72.6128,0,0,0.0,4.259,1,0,0,True
74,1.0,DZA,Algeria,2004.0,0,72.6137,0,0,0.0,3.972,1,0,0,True
75,1.0,DZA,Algeria,2005.0,0,73.3799,0,0,0.0,1.382,1,0,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,70.0,ZWE,Zimbabwe,2009.0,1,354.8000,1,1,0.0,-7.670,1,1,0,True
1055,70.0,ZWE,Zimbabwe,2010.0,0,378.2000,1,1,0.0,3.217,1,0,0,True
1056,70.0,ZWE,Zimbabwe,2011.0,0,361.9000,1,1,0.0,4.920,1,0,0,True
1057,70.0,ZWE,Zimbabwe,2012.0,0,361.9000,1,1,0.0,3.720,1,0,0,True
1058,70.0,ZWE,Zimbabwe,2013.0,0,361.9000,1,1,0.0,1.632,1,0,0,True

In [122]:
#loc tekbel taaml filtrz b les conditions
df.loc[df['year'] >2000]['country'] #['country] to get the countries that have year>2000 inly, it's a filter
#we can do df.loc[df['year'] >2000, 'country']

71       Algeria
72       Algeria
73       Algeria
74       Algeria
75       Algeria
          ...
1054    Zimbabwe
1055    Zimbabwe
1056    Zimbabwe
1057    Zimbabwe
1058    Zimbabwe
Name: country, Length: 180, dtype: object

In [123]:
df.loc[df['year'] >2000, 'country']

71       Algeria
72       Algeria
73       Algeria
74       Algeria
75       Algeria
          ...
1054    Zimbabwe
1055    Zimbabwe
1056    Zimbabwe
1057    Zimbabwe
1058    Zimbabwe
Name: country, Length: 180, dtype: object

In [124]:
df.loc[df['country']== 'Tunisia']

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
822,63.0,TUN,Tunisia,1940.0,0,49.189000,0,0,0.0,22.013002,0,0,1,True
823,63.0,TUN,Tunisia,1941.0,0,44.937000,0,0,0.0,24.582032,0,0,1,True
824,63.0,TUN,Tunisia,1942.0,0,129.831000,0,0,0.0,24.996313,0,0,1,True
825,63.0,TUN,Tunisia,1943.0,0,50.000000,0,0,0.0,72.109486,0,0,1,True
826,63.0,TUN,Tunisia,1944.0,0,55.355000,0,0,0.0,37.613107,0,1,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892,63.0,TUN,Tunisia,2010.0,0,1.437900,0,0,0.0,4.409000,1,0,0,True
893,63.0,TUN,Tunisia,2011.0,0,1.499300,0,0,0.0,3.541000,1,0,0,True
894,63.0,TUN,Tunisia,2012.0,0,1.550600,0,0,0.0,5.139000,1,0,0,True
895,63.0,TUN,Tunisia,2013.0,0,1.653096,0,0,0.0,5.805000,1,0,0,True
896,63.0,TUN,Tunisia,2014.0,0,1.862412,0,0,0.0,4.924000,1,0,0,True

In [125]:
df.loc[:,'banking_crisis'] #bl esm

0       True
1       True
2       True
3       True
4       True
        ...
1054    True
1055    True
1056    True
1057    True
1058    True
Name: banking_crisis, Length: 1059, dtype: bool

In [126]:
df.loc[:,['year','country','banking_crisis']]

        year   country  banking_crisis
0     1870.0   Algeria            True
1     1871.0   Algeria            True
2     1872.0   Algeria            True
3     1873.0   Algeria            True
4     1874.0   Algeria            True
...      ...       ...             ...
1054  2009.0  Zimbabwe            True
1055  2010.0  Zimbabwe            True
1056  2011.0  Zimbabwe            True
1057  2012.0  Zimbabwe            True
1058  2013.0  Zimbabwe            True

[1059 rows x 3 columns]

In [127]:
#double condition
df.loc[(df['country'] == 'Algeria') & (df['year'] == 2010)] #value_counts to get the occurence
#ki ma naamlouch virgule rana n filtrou b les lignes khaw mch b les colonnes 
#&: et, |: ou

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
80,1.0,DZA,Algeria,2010.0,0,74.9437,0,0,0.0,3.913,1,0,0,True

In [128]:
df_Tunisia = df.loc[df['country_code'] == 'TUN', ['country', 'banking_crisis']]
df_Tunisia

     country  banking_crisis
822  Tunisia            True
823  Tunisia            True
824  Tunisia            True
825  Tunisia            True
826  Tunisia            True
..       ...             ...
892  Tunisia            True
893  Tunisia            True
894  Tunisia            True
895  Tunisia            True
896  Tunisia            True

[75 rows x 2 columns]

Objective
In this exercise, you will work with a dataset called "employee info" that contains information about employees in a company. The dataset includes columns such as Name, Department, Age, Gender, Salary, and Experience.

Instructions
Create a dataframe called "employee_df" with the following data:

import pandas as pd

data = {'Name': ['John', 'Mary', 'Bob', 'Sarah', 'Tom', 'Lisa'], 'Department': ['IT', 'Marketing', 'Sales', 'IT', 'Finance', 'Marketing'], 'Age': [30, 40, 25, 35, 45, 28], 'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'], 'Salary': [50000, 60000, 45000, 55000, 70000, 55000], 'Experience': [3, 7, 2, 5, 10, 4]}

 employee_df = pd.DataFrame(data)

 

Use the iloc method to select the first 3 rows of the dataframe.
Use the loc method to select all rows where the Department is "Marketing".
Use the iloc method to select the Age and Gender columns for the first 4 rows of the dataframe.
Use the loc method to select the Salary and Experience columns for a

In [129]:
import pandas as pd

data = {'Name': ['John', 'Mary', 'Bob', 'Sarah', 'Tom', 'Lisa'], 'Department': ['IT', 'Marketing', 'Sales', 'IT', 'Finance', 'Marketing'], 'Age': [30, 40, 25, 35, 45, 28], 'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'], 'Salary': [50000, 60000, 45000, 55000, 70000, 55000], 'Experience': [3, 7, 2, 5, 10, 4]}

employee_df = pd.DataFrame(data)

In [130]:
employee_df

    Name Department  Age  Gender  Salary  Experience
0   John         IT   30    Male   50000           3
1   Mary  Marketing   40  Female   60000           7
2    Bob      Sales   25    Male   45000           2
3  Sarah         IT   35  Female   55000           5
4    Tom    Finance   45    Male   70000          10
5   Lisa  Marketing   28  Female   55000           4

In [131]:
#Use the iloc method to select the first 3 rows of the dataframe
employee_df.iloc[:3]

   Name Department  Age  Gender  Salary  Experience
0  John         IT   30    Male   50000           3
1  Mary  Marketing   40  Female   60000           7
2   Bob      Sales   25    Male   45000           2

In [132]:
#Use the loc method to select all rows where the Department is "Marketing".
employee_df.loc[employee_df['Department']=='Marketing']

   Name Department  Age  Gender  Salary  Experience
1  Mary  Marketing   40  Female   60000           7
5  Lisa  Marketing   28  Female   55000           4

In [133]:
#Use the iloc method to select the Age and Gender columns for the first 4 rows of the dataframe.
employee_df.iloc[:4,2:4]

   Age  Gender
0   30    Male
1   40  Female
2   25    Male
3   35  Female

In [134]:
#Use the loc method to select the department and gender columns 
employee_df.iloc[:,[1,3]]

  Department  Gender
0         IT    Male
1  Marketing  Female
2      Sales    Male
3         IT  Female
4    Finance    Male
5  Marketing  Female

## Value Counts: Occurence

In [135]:
df['banking_crisis'].value_counts() 
#the output is binary and unbalanced

banking_crisis
True    1059
Name: count, dtype: int64

In [136]:
df['country_code'].value_counts()

country_code
EGY    155
ZAF    114
ZWE     90
DZA     85
AGO     77
MAR     75
TUN     75
ZMB     72
MUS     68
KEN     67
CIV     63
NGA     60
CAF     58
Name: count, dtype: int64

In [137]:
df['independence'].value_counts()
#binary column

independence
1    822
0    237
Name: count, dtype: int64

## Unique

In [138]:
#displays the unique values. les valeurs l ytaawdou ma yjybhomch barcha marat, mara wahda 
df['country_code'].unique()

array(['DZA', 'AGO', 'CAF', 'CIV', 'EGY', 'KEN', 'MUS', 'MAR', 'NGA',
       'ZAF', 'TUN', 'ZMB', 'ZWE'], dtype=object)

In [139]:
#to determine th 'independence' col unique values
df['independence'].unique()

array([0, 1])

In [140]:
df['country'].unique()

array(['Algeria', 'Angola', 'Central African Republic', 'Ivory Coast',
       'Egypt', 'Kenya', 'Mauritius', 'Morocco', 'Nigeria',
       'South Africa', 'Tunisia', 'Zambia', 'Zimbabwe'], dtype=object)

## Replace

In [141]:
#put the values of value_counts function in a dictionary
dict_country= df['country_code'].value_counts().to_dict()
dict_country

{'EGY': 155,
 'ZAF': 114,
 'ZWE': 90,
 'DZA': 85,
 'AGO': 77,
 'MAR': 75,
 'TUN': 75,
 'ZMB': 72,
 'MUS': 68,
 'KEN': 67,
 'CIV': 63,
 'NGA': 60,
 'CAF': 58}

In [142]:
df['country_code']=df['country_code'].replace({'TUN':'TN','EGY':'EG'}) #e separateur f dict , . Nhotou l valeurs lkdima w godemha e jdida
df['country_code'].value_counts().to_dict()

{'EG': 155,
 'ZAF': 114,
 'ZWE': 90,
 'DZA': 85,
 'AGO': 77,
 'MAR': 75,
 'TN': 75,
 'ZMB': 72,
 'MUS': 68,
 'KEN': 67,
 'CIV': 63,
 'NGA': 60,
 'CAF': 58}

In [143]:
df['banking_crisis'].value_counts().to_dict()

{True: 1059}

In [144]:
df['banking_crisis']=df['banking_crisis'].map({'no_crisis':0,'crisis':1}) #map is the same as replace

In [145]:
df['banking_crisis'].value_counts().to_dict()

{}

## Checking Missing Values

In [146]:
#es cases vides
df.isnull()
#output: false= not null, true=null cell

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
0,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1055,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1056,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1057,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1058,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [147]:
#for a more professional visualization
df.isnull().sum() #display sum of null values in each column

country_number                        0
country_code                          0
country                               0
year                                  0
systemic_crisis                       0
exch_usd                              0
domestic_debt_in_default              0
sovereign_external_debt_default       0
gdp_weighted_default                  0
inflation_annual_cpi                  0
independence                          0
currency_crises                       0
inflation_crises                      0
banking_crisis                     1059
dtype: int64

In [148]:
sum(df.isnull().sum()) #to display total sum of null values

1059

In [149]:
#note: value_count() tetaba9 ala colonne vs count() tetaba9 ala variable kbira

## Duplicates (Doublement)

In [150]:
df.duplicated().sum() #total sum of duplicated rows

np.int64(0)

In [151]:
df.duplicated() #duplicates per row (if the row is duplicated or not)

0       False
1       False
2       False
3       False
4       False
        ...
1054    False
1055    False
1056    False
1057    False
1058    False
Length: 1059, dtype: bool

In [152]:
duplicates=int(df.duplicated().sum())
duplicates

0

## Aggregations (count(), size(), mean(), median(), sum())

In [153]:
df['inflation_annual_cpi'].size

1059

In [154]:
mean_inflation_rate=float(df['inflation_annual_cpi'].mean())
mean_inflation_rate

20848.892443988745

In [155]:
median_inflation_rate=float(df['inflation_annual_cpi'].median())
median_inflation_rate

5.762329909

In [156]:
total_inflation_rate=float(df['inflation_annual_cpi'].sum())
total_inflation_rate

22078977.098184083

In [157]:
float(df['gdp_weighted_default'].max()) #adding float is more professional

0.4

In [158]:
float(df['gdp_weighted_default'].min())

0.0

## Outliers-Valeurs abérantes

In [159]:
#to replace outliers by median, applicable to all datasets
from scipy.stats import zscore
import numpy as np

numeric_columns = df.select_dtypes(include=[np.number])
z_scores = np.abs(zscore(numeric_columns))
cleaned_dataset = df.copy()

#iterate over each numeric column
for col in numeric_columns.columns:
    median = numeric_columns[col].median()
    outliers = z_scores[col] > 3   #
    cleaned_dataset.loc[outliers, col] = median

df = cleaned_dataset

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices